- name: Build EXE (onefile)
  run: |
    pyinstaller --noconsole --onefile --clean ^
      --name ImageCatalog ^
      --hidden-import PIL ^
      --hidden-import PIL.Image ^
      --hidden-import PIL.ImageTk ^
      image_catalog_app.py
